title: Javier David
description: Bienvenido a mi blog

# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: # Ex: /project-page
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Inicio
      url: /index.html
    - title: Acerca de
      url: /about
    - title: Logros
      url: /achievements

social:
    github: ByJavier1403
    email: javier.hernandez@itam.mx
    linkedin: javier-david-hernández-estrada-48015b248/

disqus:
    shortname: javier1403